// Drum Kit (GM) template test — verifies the shipped multi preset:
//   * loads via the real .yml load path and re-infers as the built-in
//     Drum Kit ARRANGEMENT (the Patch page shows "Drum Kit", not "Custom"),
//   * each GM note routes to its own Part (single-note keyzones, Omni channel),
//   * every part carries its name + exactly 1 MONO voice slot (the built-in
//     preset's 6 x 1 mono contract),
//   * drum notes are audible and concurrent (a "beat" = one voice in each
//     struck drum's part),
//   * repeats retrigger the single mono voice (latest hit re-attacks, then
//     the voice frees — no stuck voice).
//
// The template itself is generated by tools/gen_templates.cpp
// (writeDrumKitTemplate: applyArrangement(DrumKit) + bespoke drum content)
// and embedded via the factory installer.

#include <cmath>
#include "unified_test_runner.h"
#include <cstdio>
#include <set>
#include <vector>

#include <juce_audio_basics/juce_audio_basics.h>
#include <juce_audio_processors/juce_audio_processors.h>
#include <juce_core/juce_core.h>
#include <juce_data_structures/juce_data_structures.h>
#include <juce_events/juce_events.h>
#include <juce_gui_basics/juce_gui_basics.h>

#include "PluginProcessor.h"
#include "SynthEngine.h"
#include "ui/PatchArrangement.h"   // inferArrangement (the Drum Kit contract)

namespace
{
int g_failures = 0;
void check (bool cond, const char* msg) { std::printf ("  %s: %s\n", cond ? "ok  " : "FAIL", msg); if (! cond) ++g_failures; }

void renderIdle (HellcatAudioProcessor& p, int blocks)
{
    for (int i = 0; i < blocks; ++i)
    {
        juce::AudioBuffer<float> buf (2, 256);
        buf.clear();
        juce::MidiBuffer midi;
        p.processBlock (buf, midi);
    }
}

float blockPeak (HellcatAudioProcessor& p, juce::MidiBuffer& midi)
{
    juce::AudioBuffer<float> buf (2, 256);
    buf.clear();
    p.processBlock (buf, midi);
    float pk = 0.0f;
    for (int ch = 0; ch < 2; ++ch)
        for (int s = 0; s < buf.getNumSamples(); ++s)
            pk = std::max (pk, std::fabs (buf.getSample (ch, s)));
    return pk;
}

struct DrumDef { const char* name; int note; int part; };
const DrumDef kKit[6] = {
    { "Kick",       36, 0 }, { "Snare",      38, 1 }, { "Clap",       39, 2 },
    { "Closed Hat", 42, 3 }, { "Open Hat",   46, 4 }, { "Tom",        45, 5 },
};

int activeInPart (SynthEngine& e, int part)
{
    int n = 0;
    for (int i = 0; i < kNumVoices; ++i)
        if (auto* av = e.getAmbikaVoice (i))
            if (av->isVoiceActive() && av->getPartIndex() == part)
                ++n;
    return n;
}
}  // namespace

TEST(drum_kit_test)
{
    std::printf ("DRUM KIT TEST\n");

    const juce::File tmpl = juce::File::getCurrentWorkingDirectory()
                                .getChildFile ("presets/TEMPLATES/Drum Kit (GM).yml");
    if (! tmpl.existsAsFile())
    {
        std::printf ("  FAIL: template not found (run hellcat_gen_templates first): %s\n",
                     tmpl.getFullPathName().toRawUTF8());
        return false;
    }

    HellcatAudioProcessor proc;
    proc.prepareToPlay (48000.0, 256);
    renderIdle (proc, 2);
    check (proc.loadHellcatMultiFile (tmpl), "Drum Kit (GM).yml loads");
    SynthEngine& engine = proc.getEngine();
    renderIdle (proc, 2);

    // ---- [a] setup: names, 1 mono slot, zones, arrangement match ----
    std::printf ("\n[a] kit setup\n");
    check (inferArrangement (engine) == Arrangement::DrumKit,
           "loaded template re-infers as the built-in Drum Kit arrangement");
    for (const auto& d : kKit)
    {
        char msg[96];
        std::snprintf (msg, sizeof (msg), "%s: part %d named", d.name, d.part);
        check (engine.getPartName (d.part) == d.name, msg);
        std::snprintf (msg, sizeof (msg), "%s: 1 voice slot", d.name);
        check (engine.getPartVoiceSlots (d.part) == 1, msg);
        std::snprintf (msg, sizeof (msg), "%s: single-note keyzone %d", d.name, d.note);
        check (engine.getPartKeyrangeLow (d.part) == d.note && engine.getPartKeyrangeHigh (d.part) == d.note, msg);
        std::snprintf (msg, sizeof (msg), "%s: one voicecard, Omni channel", d.name);
        check (engine.getPartVoiceAllocation (d.part) == (1u << d.part) && engine.getPartChannel (d.part) == 0, msg);
        std::snprintf (msg, sizeof (msg), "%s: MONO polyphony", d.name);
        check (engine.getPart (d.part).partBytes[15] == 0, msg);
    }
    check ((int) engine.getPart (0).voiceIndices.size() == 1, "slots applied (1 pool voice per part)");

    // ---- [b] each GM note triggers exactly its own part ----
    std::printf ("\n[b] GM note routing\n");
    for (const auto& d : kKit)
    {
        {   // note-on on channel 1 (Omni parts accept any channel)
            juce::MidiBuffer m;
            m.addEvent (juce::MidiMessage::noteOn (1, d.note, 0.9f), 0);
            check (blockPeak (proc, m) > 0.001f, "note is audible");
        }
        renderIdle (proc, 1);
        bool own = activeInPart (engine, d.part) > 0;
        bool others = false;
        for (int p = 0; p < kNumParts; ++p)
            if (p != d.part && activeInPart (engine, p) > 0)
                others = true;
        char msg[96];
        std::snprintf (msg, sizeof (msg), "note %d triggers only part %d (%s)", d.note, d.part, d.name);
        check (own && ! others, msg);
        {   // release + let the one-shot decay finish
            juce::MidiBuffer m;
            m.addEvent (juce::MidiMessage::noteOff (1, d.note, 0.9f), 0);
            blockPeak (proc, m);
        }
        renderIdle (proc, 300);
    }
    check (activeInPart (engine, 0) + activeInPart (engine, 1) + activeInPart (engine, 2)
           + activeInPart (engine, 3) + activeInPart (engine, 4) + activeInPart (engine, 5) == 0,
           "kit silent after all releases (one-shot decays)");

    // ---- [c] a beat: concurrent drums across parts ----
    std::printf ("\n[c] concurrent drums\n");
    {
        juce::MidiBuffer m;
        m.addEvent (juce::MidiMessage::noteOn (1, 36, 0.9f), 0);   // kick
        m.addEvent (juce::MidiMessage::noteOn (1, 38, 0.9f), 0);   // snare
        m.addEvent (juce::MidiMessage::noteOn (1, 42, 0.9f), 0);   // closed hat
        m.addEvent (juce::MidiMessage::noteOn (1, 46, 0.9f), 0);   // open hat
        check (blockPeak (proc, m) > 0.001f, "simultaneous kit notes are audible");
        renderIdle (proc, 1);
        check (activeInPart (engine, 0) == 1 && activeInPart (engine, 1) == 1
               && activeInPart (engine, 3) == 1 && activeInPart (engine, 4) == 1,
               "4 drums sounding concurrently (one voice each)");
        juce::MidiBuffer off;
        off.addEvent (juce::MidiMessage::noteOff (1, 36, 0.9f), 0);
        off.addEvent (juce::MidiMessage::noteOff (1, 38, 0.9f), 0);
        off.addEvent (juce::MidiMessage::noteOff (1, 42, 0.9f), 0);
        off.addEvent (juce::MidiMessage::noteOff (1, 46, 0.9f), 0);
        blockPeak (proc, off);
        renderIdle (proc, 300);
    }

    // ---- [d] fast repeats retrigger the single MONO voice ----
    std::printf ("\n[d] repeat retriggering\n");
    {
        // With 1 voice slot + MONO, 4 same-block note-ons of note 46 all route
        // to the part's single voice: the latest hit RETRIGGERS it (mono
        // re-attack — no stacking, exactly one voice ever sounds).
        juce::MidiBuffer on;
        for (int hit = 0; hit < 4; ++hit)
            on.addEvent (juce::MidiMessage::noteOn (1, 46, 0.9f), hit);   // open hat
        check (blockPeak (proc, on) > 0.001f, "open-hat retriggers are audible");
        renderIdle (proc, 1);
        check (activeInPart (engine, 4) == 1,
               "same-block repeats retrigger the single voice (never stack)");
        juce::MidiBuffer offM;
        for (int hit = 0; hit < 4; ++hit)
            offM.addEvent (juce::MidiMessage::noteOff (1, 46, 0.9f), hit);   // one off per hit (as real drum MIDI)
        blockPeak (proc, offM);
        renderIdle (proc, 300);
        check (activeInPart (engine, 4) == 0, "the single voice frees after the one-shot decays (no stuck voice)");
    }

    std::printf ("\nDRUM KIT TEST: %s (%d failures)\n",
                 g_failures == 0 ? "ALL CHECKS PASSED" : "FAILURES", g_failures);
    return g_failures == 0;
}
