// Copyright (c) 2024 805LABS / Parvati.  See FactoryPresetInstaller.h.

#include "FactoryPresetInstaller.h"

#include "BinaryData.h"   // generated by juce_add_binary_data (namespace FactoryPresets)

#include <atomic>
#include <mutex>

namespace parvati
{
namespace
{
// Process-once guard: extraction (and its directory scan) runs at most once per
// process, even though tests / hosts create many AudioProcessors.
std::once_flag g_installOnceFlag;
std::atomic<bool> g_installDone { false };
// Write one embedded resource to disk if it is not already present.
// Returns true if the file was written.
bool writeIfMissing (const juce::File& target, const char* data, int size)
{
    if (target.exists())
        return false;
    if (! target.getParentDirectory().createDirectory())
        return false;
    juce::TemporaryFile temp (target);
    {
        juce::FileOutputStream out (temp.getFile());
        if (! out.openedOk() || ! out.write (data, (size_t) size))
            return false;
        out.flush();
    }
    return temp.overwriteTargetFileWithTemporary();
}

// Does @p dir already hold at least one preset of @p wildcard? (cheap existence
// gate so an installed tree is never re-scanned).
bool dirHasPresets (const juce::File& dir, const char* wildcard)
{
    if (! dir.isDirectory())
        return false;
    juce::Array<juce::File> files;
    dir.findChildFiles (files, juce::File::findFiles, false, wildcard);
    return ! files.isEmpty();
}
}  // namespace

int ensureFactoryPresetsInstalled (const juce::File& factoryDir,
                                   const juce::File& factoryMultiDir,
                                   const juce::File& templatesDir,
                                   const juce::File& userDir)
{
    // Process-once: run the directory scan / extraction at most once. After the
    // first call this is a single relaxed atomic load (free for the many
    // AudioProcessors tests/hosts create).
    if (g_installDone.load (std::memory_order_relaxed))
        return 0;

    int written = 0;
    std::call_once (g_installOnceFlag, [&]
    {
        // Always provide a USER area for the user's own saved presets.
        userDir.createDirectory();
        templatesDir.createDirectory();

        // Legacy cleanup (pre-release): the previous flat layout extracted to
        // Parvati/Factory and Parvati/FactoryMulti. Those are superseded by
        // FACTORY/<bank>/ and FACTORY_MULTI/, so remove the old flat dirs once.
        // Only the two known legacy names are touched. On a CASE-INSENSITIVE FS
        // (default macOS APFS) "Factory" and "FACTORY" are the same directory,
        // so compare the paths case-insensitively and never delete a dir that is
        // (case-insensitively) the live factory/multi dir.
        const auto sameDirCI = [] (const juce::File& a, const juce::File& b)
        {
            return a.getFullPathName().toLowerCase() == b.getFullPathName().toLowerCase();
        };
        const juce::File base = factoryDir.getParentDirectory();
        const juce::File legacyFactory = base.getChildFile ("Factory");
        const juce::File legacyMulti   = base.getChildFile ("FactoryMulti");
        if (! sameDirCI (legacyFactory, factoryDir))
            legacyFactory.deleteRecursively (false);
        if (! sameDirCI (legacyMulti, factoryMultiDir))
            legacyMulti.deleteRecursively (false);

        // If BOTH new directories already carry presets, there is nothing to do.
        const bool proPresent = dirHasPresets (factoryDir,     "*.PRO");
        const bool mulPresent = dirHasPresets (factoryMultiDir, "*.MUL");
        const bool tplPresent = dirHasPresets (templatesDir,   "*.parvati");
        if (proPresent && mulPresent && tplPresent)
            return;

        for (int i = 0; i < FactoryPresets::namedResourceListSize; ++i)
        {
            const char* const resourceName = FactoryPresets::namedResourceList[i];
            int size = 0;
            const char* const data = FactoryPresets::getNamedResource (resourceName, size);
            if (data == nullptr || size <= 0)
                continue;

            const char* const originalName =
                FactoryPresets::getNamedResourceOriginalFilename (resourceName);
            if (originalName == nullptr)
                continue;

            const juce::String name (originalName);
            // The staged name encodes the bank: "A__000.PRO" (bank A),
            // "MULTI__000.MUL" (a multi). Split at the first "__": token before,
            // filename after. token == MULTI -> FACTORY_MULTI/<file>; else the
            // token is a bank (A/B/F/S) -> FACTORY/<bank>/<file>.
            const int sep = name.indexOf ("__");
            juce::File target;
            if (sep > 0 && sep < name.length() - 2)
            {
                const juce::String token = name.substring (0, sep);
                const juce::String fname = name.substring (sep + 2);
                if (token == "MULTI")
                    target = factoryMultiDir.getChildFile (fname);
                else if (token == "TEMPLATE")
                    target = templatesDir.getChildFile (fname);
                else
                    target = factoryDir.getChildFile (token).getChildFile (fname);
            }
            else
            {
                // Fallback (un-prefixed name): route by extension as before.
                target = name.endsWithIgnoreCase (".MUL") ? factoryMultiDir
                                                          : factoryDir;
                target = target.getChildFile (name);
            }
            if (writeIfMissing (target, data, size))
                ++written;
        }
    });

    g_installDone.store (true, std::memory_order_relaxed);
    return written;
}
}  // namespace parvati
