// Copyright (c) 2024 805LABS / Parvati.  See FactoryPresetInstaller.h.

#include "FactoryPresetInstaller.h"

#include "BinaryData.h"   // generated by juce_add_binary_data (namespace FactoryPresets)

#include <atomic>
#include <mutex>

namespace parvati
{
namespace
{
// Process-once guard: extraction (and its directory scan) runs at most once per
// process, even though tests / hosts create many AudioProcessors.
std::once_flag g_installOnceFlag;
std::atomic<bool> g_installDone { false };
// Write one embedded resource to disk if it is not already present.
// Returns true if the file was written.
bool writeIfMissing (const juce::File& target, const char* data, int size)
{
    if (target.exists())
        return false;
    if (! target.getParentDirectory().createDirectory())
        return false;
    juce::TemporaryFile temp (target);
    {
        juce::FileOutputStream out (temp.getFile());
        if (! out.openedOk() || ! out.write (data, (size_t) size))
            return false;
        out.flush();
    }
    return temp.overwriteTargetFileWithTemporary();
}

// Does @p dir already hold at least one preset of @p wildcard? (cheap existence
// gate so an installed tree is never re-scanned).
bool dirHasPresets (const juce::File& dir, const char* wildcard)
{
    if (! dir.isDirectory())
        return false;
    juce::Array<juce::File> files;
    dir.findChildFiles (files, juce::File::findFiles, false, wildcard);
    return ! files.isEmpty();
}
}  // namespace

int ensureFactoryPresetsInstalled (const juce::File& factoryDir,
                                   const juce::File& factoryMultiDir)
{
    // Process-once: run the directory scan / extraction at most once. After the
    // first call this is a single relaxed atomic load (free for the many
    // AudioProcessors tests/hosts create).
    if (g_installDone.load (std::memory_order_relaxed))
        return 0;

    int written = 0;
    std::call_once (g_installOnceFlag, [&]
    {
        // If BOTH directories already carry presets, there is nothing to do.
        const bool proPresent = dirHasPresets (factoryDir,     "*.PRO");
        const bool mulPresent = dirHasPresets (factoryMultiDir, "*.MUL");
        if (proPresent && mulPresent)
            return;

        for (int i = 0; i < FactoryPresets::namedResourceListSize; ++i)
        {
            const char* const resourceName = FactoryPresets::namedResourceList[i];
            int size = 0;
            const char* const data = FactoryPresets::getNamedResource (resourceName, size);
            if (data == nullptr || size <= 0)
                continue;

            const char* const originalName =
                FactoryPresets::getNamedResourceOriginalFilename (resourceName);
            if (originalName == nullptr)
                continue;

            const juce::String name (originalName);
            // Route by extension: .PRO -> Factory, .MUL -> FactoryMulti.
            const juce::File targetDir = name.endsWithIgnoreCase (".MUL") ? factoryMultiDir
                                                                          : factoryDir;
            if (writeIfMissing (targetDir.getChildFile (name), data, size))
                ++written;
        }
    });

    g_installDone.store (true, std::memory_order_relaxed);
    return written;
}
}  // namespace parvati
