#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# tools/new_test.sh — deterministic scaffolder for the unified test suite.
# ---------------------------------------------------------------------------
# Usage:   tools/new_test.sh <test_name>
#
# Creates tests/<test_name>.cpp from a minimal template (unified_test_runner.h
# + test_utils.h, one CHECK example) and registers it in the ONE test binary's
# source list in CMakeLists.txt, right after the anchor comment:
#     # Unified test sources (keep alphabetical-ish; new_test.sh appends here)
#
# It NEVER creates a per-test executable target — the suite is a single
# hellcat_unified_tests binary, and the configure-time orphan guard
# (CMakeLists.txt, "Single-binary test policy") fails configure if a tests/
# *.cpp is not in that one source list. This script exists so adding a test
# is one deterministic command instead of a hand edit that can reintroduce
# the 100-binaries sprawl.
#
# Determinism: set -euo pipefail, no prompts, no backup files. All validation
# happens before any write; the CMake edit goes through a temp file + mv and a
# failed run leaves the tree unchanged.
# ---------------------------------------------------------------------------
set -euo pipefail

usage() { echo "usage: tools/new_test.sh <test_name>" >&2; exit 2; }

[ $# -eq 1 ] || usage
name="$1"

# --- Validation (all before any write) -------------------------------------
# Lowercase snake_case. The letter of the character class is [a-z0-9_]+, but a
# leading digit would make TEST(<name>) an invalid C identifier; reject it
# with a clear message. Harness/reserved names are off-limits too.
if ! [[ "$name" =~ ^[a-z0-9_]+$ ]]; then
    echo "ERROR: '$name' is not lowercase snake_case ([a-z0-9_]+)." >&2
    exit 1
fi
if [[ "$name" =~ ^[0-9] ]]; then
    echo "ERROR: '$name' starts with a digit — TEST($name) would not be a valid C identifier." >&2
    exit 1
fi
if [[ "$name" == unified_test_* ]]; then
    echo "ERROR: '$name' collides with the harness namespace (unified_test_*)." >&2
    exit 1
fi
if [ -e "tests/${name}.cpp" ]; then
    echo "ERROR: tests/${name}.cpp already exists." >&2
    exit 1
fi
if grep -qF "tests/${name}.cpp" CMakeLists.txt; then
    echo "ERROR: tests/${name}.cpp is already referenced in CMakeLists.txt (name taken)." >&2
    exit 1
fi

created_test_file=""
cleanup() {
    [ -n "$created_test_file" ] && rm -f "$created_test_file"
}
trap cleanup EXIT

# --- 1. Generate the test file ----------------------------------------------
created_test_file="tests/${name}.cpp"
cat > "$created_test_file" <<EOF
// ${name} — one-line purpose goes here.
//
// Generated by tools/new_test.sh. Replace this placeholder body with real
// assertions. The suite is ONE binary (hellcat_unified_tests): there are no
// per-test executable targets, and the configure-time orphan guard fails
// configure if a tests/*.cpp is not in that binary's source list.

#include <cstdio>

#include "test_utils.h"          // setInt/setChoice/setParam host-style writes
#include "unified_test_runner.h"

TEST(${name})
{
    // CHECK(cond, msg) fails the test when cond is false; remove this example.
    CHECK(true, "scaffold placeholder — replace with the first real assertion");

    // Example host-style parameter write (see tests/test_utils.h):
    //   HellcatAudioProcessor proc;
    //   proc.prepareToPlay (48000.0, 256);
    //   setInt (proc, "some_int_param_id", 42);

    return true;
}
EOF

# --- 2. Register in the unified source list (temp file + mv) ----------------
ANCHOR='# Unified test sources (keep alphabetical-ish; new_test.sh appends here)'
entry="    tests/${name}.cpp"

tmp="$(mktemp)"
if grep -qF "$ANCHOR" CMakeLists.txt; then
    # Insert right after the existing anchor line.
    awk -v anchor="$ANCHOR" -v entry="$entry" '
        { print }
        index($0, anchor) == 1 { print entry; inserted = 1 }
        END { exit inserted ? 0 : 3 }
    ' CMakeLists.txt > "$tmp" || { echo "ERROR: anchor found by grep but not by awk — aborting." >&2; exit 1; }
else
    # Anchor not present yet: add it (plus the new entry) directly after the
    # last migrated plain test source, before the vendored firmware block.
    awk -v anchor="$ANCHOR" -v entry="$entry" '
        index($0, "    tests/hellcat_retrig_probe.cpp") == 1 { print; print anchor; print entry; inserted = 1; next }
        { print }
        END { exit inserted ? 0 : 3 }
    ' CMakeLists.txt > "$tmp" || { echo "ERROR: anchor insertion point (tests/hellcat_retrig_probe.cpp) not found — aborting." >&2; exit 1; }
fi

# The edit must register the new source exactly once (validation above
# guarantees it was absent before).
count_before="$(grep -cF "$entry" CMakeLists.txt || true)"
count_after="$(grep -cF "$entry" "$tmp" || true)"
if [ "$count_before" != "0" ] || [ "$count_after" != "1" ]; then
    echo "ERROR: CMakeLists.txt edit did not add exactly one '$entry' line (before=${count_before}, after=${count_after}) — aborting." >&2
    exit 1
fi
mv "$tmp" CMakeLists.txt
created_test_file=""   # success: nothing to roll back

# --- 3. Next steps -----------------------------------------------------------
echo "Created  tests/${name}.cpp and registered it in hellcat_unified_tests."
echo
echo "Next steps:"
echo "  cmake --build build_unified --target hellcat_unified_tests -j8"
echo "  ./build_unified/hellcat_unified_tests ${name}"
echo
echo "Do NOT create a per-test executable target for this test — the suite is ONE binary"
echo "(the configure-time orphan guard enforces it)."
